import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { BodyVisibilityProvider } from "@/contexts/BodyVisibility";
import { Footer } from "@/sections/shared/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Coscharis-Group Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} h-full antialiased`}
    >
      <BodyVisibilityProvider>
        <body className="min-h-full flex flex-col">
          <Navbar />
          {children}
          <Footer />
        </body>
      </BodyVisibilityProvider>
    </html>
  );
}
// px-10 max-[541px]:px-5
