import { FeaturedNews, Vehicle } from "./types";

export const BusinessesSectors = [
  "Motors",
  "Technologies",
  "Mobility",
  "Beverages",
  "Medicine & Food",
  "Farms",
];

export const FeaturedCars: Vehicle[] = [
  {
    name: "2022 Renault Fluence",
    mainImage:
      "https://www.pngarts.com/files/1/Renault-PNG-Transparent-Image.png",
    category: "Compact Sudan",
    keySpecs: ["manual", "4 doors", "110hp", "sedan", "5.3L"],
    startingPrice: 53000000,
    detailShots: [
      "https://www.pngarts.com/files/1/Renault-PNG-Transparent-Image.png",
      "https://picsum.photos/id/32/818/540",
      "https://picsum.photos/id/61/818/540",
      "https://picsum.photos/id/68/818/540",
      "https://picsum.photos/id/72/818/540",
      "https://picsum.photos/id/79/818/540",
      "https://picsum.photos/id/91/818/540",
      "https://picsum.photos/id/96/818/540",
      "https://picsum.photos/id/183/818/540",
      "https://picsum.photos/id/237/818/540",
      "https://picsum.photos/id/232/818/540",
    ],
    performanceSpecs: {
      engine: "32-valve DOHC V8 engine",
      horsepower: "355 hp",
      torque: "250 Nm",
      "0-100km/h": "6.5s",
      weight: "3300 lb",
      transmission: "automatic",
      top_speed: "220 km/h",
      fuel_tank_capacity: "90 L",
      engin_displacement: "3 L",
    },
    dimensions: {
      length: "4932 mm",
      width: "2104 mm",
      height: "1744 mm",
      wheel_base: "2,982 mm",
      ground_clearance: "214 mm",
      seats: "5",
      boot_space: "650 L",
      gross_vehicle_weight: "4468 lb",
    },
    justArrived: false,
  },
  {
    name: "2023 Land Rover Defender",
    mainImage: "https://www.pngarts.com/files/3/Land-Rover-PNG-Pic.png",
    category: "Luxury SUV",
    keySpecs: ["4x4 drive", "5 Seats", "300hp", "Automatic", "3.5L", "suv"],
    startingPrice: 35000000,
    detailShots: [
      "https://www.pngarts.com/files/3/Land-Rover-PNG-Pic.png",
      "https://picsum.photos/id/32/818/540",
      "https://picsum.photos/id/61/818/540",
      "https://picsum.photos/id/68/818/540",
      "https://picsum.photos/id/72/818/540",
      "https://picsum.photos/id/79/818/540",
      "https://picsum.photos/id/91/818/540",
      "https://picsum.photos/id/96/818/540",
      "https://picsum.photos/id/183/818/540",
      "https://picsum.photos/id/237/818/540",
      "https://picsum.photos/id/232/818/540",
    ],
    performanceSpecs: {
      engine: "32-valve DOHC V8 engine",
      horsepower: "355 hp",
      torque: "250 Nm",
      "0-100km/h": "6.5s",
      weight: "3300 lb",
      transmission: "automatic",
      top_speed: "220 km/h",
      fuel_tank_capacity: "90 L",
      engin_displacement: "3 L",
    },
    dimensions: {
      length: "4932 mm",
      width: "2104 mm",
      height: "1744 mm",
      wheel_base: "2,982 mm",
      ground_clearance: "214 mm",
      seats: "5",
      boot_space: "650 L",
      gross_vehicle_weight: "4468 lb",
    },
    justArrived: false,
  },
  {
    name: "2024 BMW X5",
    mainImage: "https://www.pngarts.com/files/4/BMW-PNG-Download-Image.png",
    category: "Premium SUV",
    keySpecs: ["automatic", "5 seats", "335hp", "suv", "4.5L"],
    startingPrice: 42000000,
    detailShots: [
      "https://picsum.photos/id/61/818/540",
      "https://picsum.photos/id/32/818/540",
      "https://picsum.photos/id/61/818/540",
      "https://picsum.photos/id/68/818/540",
      "https://picsum.photos/id/72/818/540",
      "https://picsum.photos/id/79/818/540",
      "https://picsum.photos/id/91/818/540",
      "https://picsum.photos/id/96/818/540",
      "https://picsum.photos/id/183/818/540",
      "https://picsum.photos/id/237/818/540",
      "https://picsum.photos/id/232/818/540",
    ],
    performanceSpecs: {
      engine: "32-valve DOHC V8 engine",
      horsepower: "355 hp",
      torque: "250 Nm",
      "0-100km/h": "6.5s",
      weight: "3300 lb",
      transmission: "automatic",
      top_speed: "220 km/h",
      fuel_tank_capacity: "90 L",
      engin_displacement: "3 L",
    },
    dimensions: {
      length: "4932 mm",
      width: "2104 mm",
      height: "1744 mm",
      wheel_base: "2,982 mm",
      ground_clearance: "214 mm",
      seats: "5",
      boot_space: "650 L",
      gross_vehicle_weight: "4468 lb",
    },
    justArrived: true,
  },
  {
    name: "2022 Ford Mustang",
    mainImage: "https://www.pngarts.com/files/3/Ford-Mustang-PNG-Image.png",
    category: "Sports Coupe",
    keySpecs: ["automatic", "2 doors", "450hp", "performance coup", "5L"],
    startingPrice: 30000000,
    detailShots: [
      "https://www.pngarts.com/files/3/Ford-Mustang-PNG-Image.png",
      "https://picsum.photos/id/32/818/540",
      "https://picsum.photos/id/61/818/540",
      "https://picsum.photos/id/68/818/540",
      "https://picsum.photos/id/72/818/540",
      "https://picsum.photos/id/79/818/540",
      "https://picsum.photos/id/91/818/540",
      "https://picsum.photos/id/96/818/540",
      "https://picsum.photos/id/183/818/540",
      "https://picsum.photos/id/237/818/540",
      "https://picsum.photos/id/232/818/540",
    ],
    performanceSpecs: {
      engine: "32-valve DOHC V8 engine",
      horsepower: "355 hp",
      torque: "250 Nm",
      "0-100km/h": "6.5s",
      weight: "3300 lb",
      transmission: "automatic",
      top_speed: "220 km/h",
      fuel_tank_capacity: "90 L",
      engin_displacement: "3 L",
    },
    dimensions: {
      length: "4932 mm",
      width: "2104 mm",
      height: "1744 mm",
      wheel_base: "2,982 mm",
      ground_clearance: "214 mm",
      seats: "5",
      boot_space: "650 L",
      gross_vehicle_weight: "4468 lb",
    },
    justArrived: false,
  },
  {
    name: "2024 Rolls Royce Ghost",
    mainImage:
      "https://www.pngarts.com/files/3/White-Rolls-Royce-PNG-Background-Image.png",
    category: "Ultra Luxury Sedan",
    keySpecs: ["automatic", "4 doors", "563hp", "luxury sedan", "4L"],
    startingPrice: 150000000,
    detailShots: [
      "https://www.pngarts.com/files/3/White-Rolls-Royce-PNG-Background-Image.png",
      "https://picsum.photos/id/32/818/540",
      "https://picsum.photos/id/61/818/540",
      "https://picsum.photos/id/68/818/540",
      "https://picsum.photos/id/72/818/540",
      "https://picsum.photos/id/79/818/540",
      "https://picsum.photos/id/91/818/540",
      "https://picsum.photos/id/96/818/540",
      "https://picsum.photos/id/183/818/540",
      "https://picsum.photos/id/237/818/540",
      "https://picsum.photos/id/232/818/540",
    ],
    performanceSpecs: {
      engine: "32-valve DOHC V8 engine",
      horsepower: "355 hp",
      torque: "250 Nm",
      "0-100km/h": "6.5s",
      weight: "3300 lb",
      transmission: "automatic",
      top_speed: "220 km/h",
      fuel_tank_capacity: "90 L",
      engin_displacement: "3 L",
    },
    dimensions: {
      length: "4932 mm",
      width: "2104 mm",
      height: "1744 mm",
      wheel_base: "2,982 mm",
      ground_clearance: "214 mm",
      seats: "5",
      boot_space: "650 L",
      gross_vehicle_weight: "4468 lb",
    },
    justArrived: false,
  },
  {
    name: "2024 Toyota Land Cruiser",
    mainImage:
      "https://www.pngarts.com/files/4/Toyota-PNG-Image-Background.png",
    category: "Off-Road SUV",
    keySpecs: ["4x4 drive", "7 seats", "381hp", "suv", "3L"],
    startingPrice: 28000000,
    detailShots: [
      "https://www.pngarts.com/files/4/Toyota-PNG-Image-Background.png",
      "https://picsum.photos/id/32/818/540",
      "https://picsum.photos/id/61/818/540",
      "https://picsum.photos/id/68/818/540",
      "https://picsum.photos/id/72/818/540",
      "https://picsum.photos/id/79/818/540",
      "https://picsum.photos/id/91/818/540",
      "https://picsum.photos/id/96/818/540",
      "https://picsum.photos/id/183/818/540",
      "https://picsum.photos/id/237/818/540",
      "https://picsum.photos/id/232/818/540",
    ],
    performanceSpecs: {
      engine: "32-valve DOHC V8 engine",
      horsepower: "355 hp",
      torque: "250 Nm",
      "0-100km/h": "6.5s",
      weight: "3300 lb",
      transmission: "automatic",
      top_speed: "220 km/h",
      fuel_tank_capacity: "90 L",
      engin_displacement: "3 L",
    },
    dimensions: {
      length: "4932 mm",
      width: "2104 mm",
      height: "1744 mm",
      wheel_base: "2,982 mm",
      ground_clearance: "214 mm",
      seats: "5",
      boot_space: "650 L",
      gross_vehicle_weight: "4468 lb",
    },
    justArrived: true,
  },
  {
    name: "2023 BMW M3",
    mainImage: "https://www.pngarts.com/files/4/BMW-PNG-Image-Background.png",
    category: "Performance Sedan",
    keySpecs: ["RWD", "4 doors", "473hp", "sport coupe", "5L"],
    startingPrice: 55000000,
    detailShots: [
      "https://www.pngarts.com/files/4/BMW-PNG-Image-Background.png",
      "https://picsum.photos/id/32/818/540",
      "https://picsum.photos/id/61/818/540",
      "https://picsum.photos/id/68/818/540",
      "https://picsum.photos/id/72/818/540",
      "https://picsum.photos/id/79/818/540",
      "https://picsum.photos/id/91/818/540",
      "https://picsum.photos/id/96/818/540",
      "https://picsum.photos/id/183/818/540",
      "https://picsum.photos/id/237/818/540",
      "https://picsum.photos/id/232/818/540",
    ],
    performanceSpecs: {
      engine: "32-valve DOHC V8 engine",
      horsepower: "355 hp",
      torque: "250 Nm",
      "0-100km/h": "6.5s",
      weight: "3300 lb",
      transmission: "automatic",
      top_speed: "220 km/h",
      fuel_tank_capacity: "90 L",
      engin_displacement: "3 L",
    },
    dimensions: {
      length: "4932 mm",
      width: "2104 mm",
      height: "1744 mm",
      wheel_base: "2,982 mm",
      ground_clearance: "214 mm",
      seats: "5",
      boot_space: "650 L",
      gross_vehicle_weight: "4468 lb",
    },
    justArrived: true,
  },
  {
    name: "2023 Jaguar F-Pace",
    mainImage: "https://www.pngarts.com/files/4/BMW-PNG-Image-Background.png",
    category: "Performance Crossover",
    keySpecs: ["AWD", "5 seats", "296hp", "sedan", "4.2L"],
    startingPrice: 38000000,
    detailShots: [
      "https://www.pngarts.com/files/4/BMW-PNG-Image-Background.png",
      "https://picsum.photos/id/32/818/540",
      "https://picsum.photos/id/61/818/540",
      "https://picsum.photos/id/68/818/540",
      "https://picsum.photos/id/72/818/540",
      "https://picsum.photos/id/79/818/540",
      "https://picsum.photos/id/91/818/540",
      "https://picsum.photos/id/96/818/540",
      "https://picsum.photos/id/183/818/540",
      "https://picsum.photos/id/237/818/540",
      "https://picsum.photos/id/232/818/540",
    ],
    performanceSpecs: {
      engine: "32-valve DOHC V8 engine",
      horsepower: "355 hp",
      torque: "250 Nm",
      "0-100km/h": "6.5s",
      weight: "3300 lb",
      transmission: "automatic",
      top_speed: "220 km/h",
      fuel_tank_capacity: "90 L",
      engin_displacement: "3 L",
    },
    dimensions: {
      length: "4932 mm",
      width: "2104 mm",
      height: "1744 mm",
      wheel_base: "2,982 mm",
      ground_clearance: "214 mm",
      seats: "5",
      boot_space: "650 L",
      gross_vehicle_weight: "4468 lb",
    },
    justArrived: false,
  },
];

export const Businesses = [
  {
    id: "motors",
    name: "Motors",
    kicker: "Flagship Distribution",
    description:
      "A high-visibility automotive business built around premium vehicle brands, nationwide reach, and dependable aftersales support that keeps customers moving.",
    eyebrow: "01",
    imageSrc: "https://picsum.photos/id/177/1920/1080",
    stat: "Nationwide",
    statLabel: "Sales and service footprint",
    highlights: [
      "Vehicle sales, financing support, and fleet relationships",
      "Aftersales, parts distribution, and workshop excellence",
      "A brand experience designed to feel premium at every touchpoint",
    ],
    pageLinkSrc: "/divisions/motors",
  },
  {
    id: "technologies",
    name: "Technologies",
    kicker: "Enterprise Solutions",
    description:
      "Technology operations focused on infrastructure, devices, and business systems that help modern organizations run smarter, faster, and more reliably.",
    eyebrow: "02",
    imageSrc: "https://picsum.photos/id/2/1920/1080",
    stat: "Connected",
    statLabel: "Digital systems for modern operations",
    highlights: [
      "Enterprise hardware, deployment, and support services",
      "Solutions built for resilience, security, and continuity",
      "Technology partnerships that turn complexity into confidence",
    ],
    pageLinkSrc: "/divisions/no-demo",
  },
  {
    id: "mobility",
    name: "Mobility",
    kicker: "Movement At Scale",
    description:
      "Integrated mobility solutions designed to improve how people, fleets, and goods move through busy markets with speed, reliability, and care.",
    eyebrow: "03",
    imageSrc: "https://picsum.photos/id/55/1920/1080",
    stat: "Always On",
    statLabel: "Transport solutions with operational depth",
    highlights: [
      "Fleet-driven thinking for demanding commercial needs",
      "Customer-first mobility experiences across touchpoints",
      "Systems that prioritize uptime, service quality, and trust",
    ],
    pageLinkSrc: "/divisions/no-demo",
  },
  {
    id: "beverages",
    name: "Beverages",
    kicker: "Consumer Reach",
    description:
      "A consumer-facing business with room for storytelling, shelf presence, and brand-building across retail channels and high-frequency purchase moments.",
    eyebrow: "04",
    imageSrc: "https://picsum.photos/id/98/1920/1080",
    stat: "Everyday",
    statLabel: "Brands built for visibility and repeat demand",
    highlights: [
      "Retail distribution with strong market-facing energy",
      "Products positioned for memorability and repeat purchase",
      "Execution that balances reach, consistency, and freshness",
    ],
    pageLinkSrc: "/divisions/no-demo",
  },
  {
    id: "medicine-foods",
    name: "Medicine & Foods",
    kicker: "Essential Supply",
    description:
      "Critical product categories delivered with care, consistency, and strong operational discipline across health and nutrition needs.",
    eyebrow: "05",
    imageSrc:
      "https://coscharisgroup.net/wp-content/themes/coscharis1/images/77.jpg",
    stat: "Trusted",
    statLabel: "Essential categories handled responsibly",
    highlights: [
      "Operations built for compliance, reliability, and care",
      "Supply chains that support product confidence",
      "A practical business with meaningful everyday impact",
    ],
    pageLinkSrc: "/divisions/no-demo",
  },
  {
    id: "farms",
    name: "Farms",
    kicker: "Agricultural Value",
    description:
      "Agricultural investments and production activities shaped around long-term sustainability, food systems, and dependable execution in the field.",
    eyebrow: "06",
    imageSrc: "https://picsum.photos/id/10/1920/1080",
    stat: "Grounded",
    statLabel: "Long-horizon thinking backed by real operations",
    highlights: [
      "Production-led execution with durable market relevance",
      "A long-term play in value creation and resilience",
      "Sustainability and stewardship built into the business story",
    ],
    pageLinkSrc: "/divisions/no-demo",
  },
];

export const FeaturedNewsFeeds: FeaturedNews[] = [
  {
    title:
      "Coscharis Motors Plc unveils the new Renault Taliant at Abuja international motor fair",
    excerpt:
      "Coscharis Motors Plc., a leading automobile dealer and the exclusive representative of Renault brand in Nigeria, has once again demonstrated its industry leadership by unveiling the all-new Renault Taliant at the recently concluded Abuja International Motor Fair.",
    category: "development",
    imageSrc: "/images/headline-img.jpg",
    imageAlt: "Renault Taliant unveiling at Abuja international motor fair",
    href: "",
  },
  {
    title: "Coscharis Group promises value for money",
    excerpt:
      "Rising from a two day strategy retreat session, members of Board of Directors of all the Companies within the Coscharis Group have resolved to further deliver value for money to their numerous customers in all ramifications of their customer engagement.",
    category: "empowerment",
    imageSrc: "/images/news1-image.jpg",
    imageAlt: "Coscharis Group board strategy retreat",
    href: "",
  },
  {
    title: "Geely Global relaunches in Nigeria with Coscharis Motors plc",
    excerpt:
      "Geely Auto International Corporation has named Coscharis Motors as its official retail partner in Nigeria. Consequently, Coscharis Motors becomes the exclusive franchise representative of Geely Global in Nigeria and sets to officially launch the latest Geely models into the Nigerian market very soon.",
    category: "empowerment",
    imageSrc: "/images/news2-image.jpg",
    imageAlt: "Geely Global relaunch with Coscharis Motors",
    href: "",
  },
  {
    title:
      "Coscharis Technologies Limited announces $4 billion green power project in Nigeria",
    excerpt:
      "Coscharis Technologies Limited a subsidiary of the Coscharis Group and a leading player in the Information Communication and Technology sector in Nigeria and the Sub-Saharan Africa is an authorized distributor of a wide number of globally respected IT brands delivering reliable hardware and service solutions.",
    category: "empowerment",
    imageSrc:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuARBG8RngJ4SfecfW4OzC9n4EDjRiJHnfIBMh4bAj8L3pMrX3WXU8IN2n9plBfvY-pwfHRfMGGfgAP4cn67jw3CO4ZAebTZ91InyEaHxqwa-VO8qf0tHEAXBOjbyQklPcij9dCqjLSdqgGJKmXw3k65CI6zXnD3ktXnoSD3nqfr1fauIi4jGNa2hOZ7XgZBo-fnCPiNsX15kJEBmRmRyW6gEt20tNgf-u4_rzOO6zb6YVR9Td0nWq__xlvThkiJ_F0d7e388trlWqE",
    imageAlt: "Coscharis Technologies green power project",
    href: "",
  },
  {
    title:
      "Coscharis Group founder inducted as fellow, chartered institute of directors, Nigeria",
    excerpt:
      "The President/CEO of Coscharis Group, Dr. Cosmas Maduka, CON, was recently conferred with the prestigious Fellow of the Chartered Institute of Directors, Nigeria in recognition for his exceptional contribution to Corporate Governance and Leadership at the Institute's 2024 Fellow's Night and Investiture Ceremony in Lagos.",
    category: "empowerment",
    imageSrc: "/images/news4-image.jpg",
    imageAlt:
      "Coscharis Group founder at chartered institute of directors event",
    href: "",
  },
];

export const CoscharisMotorsServices = [
  {
    eyebrow: "01",
    title: "New & Second-Hand Vehicle Sales",
    description:
      "Explore our extensive inventory of new and pre-owned vehicles, including sedans, SUVs, trucks, and luxury cars. Our knowledgeable sales team is here to help you find the perfect vehicle that suits your needs and budget.",
  },
  {
    eyebrow: "02",
    title: "After-Sales & Maintenance",
    description:
      "Our state-of-the-art service center is staffed with certified technicians who provide comprehensive maintenance and repair services. From routine oil changes to complex engine repairs, we ensure your vehicle stays in optimal condition.",
  },
  {
    eyebrow: "03",
    title: "Vehicle Assembly",
    description:
      "We offer flexible financing solutions to make your vehicle purchase affordable. Our finance experts work with a network of lenders to secure competitive rates and terms that fit your budget.",
  },
  {
    eyebrow: "04",
    title: "Genuine Parts & AutoCare",
    description:
      "We provide a wide range of genuine parts and accessories to keep your vehicle running smoothly. Whether you need replacement parts or want to customize your vehicle, we have you covered with high-quality products.",
  },
];
